jest.config.ts
package.json

1. jest 설치
2. supertest 설치 (e2e 테스트용)

config#9 : jest 환경 설정

---

.github/ISSUE_TEMPLATE/refactoring-issue.md

docs : refactoring issue template 생성

docs : refactoring issue template 생성

---

src/index.ts
src/user/index.ts
tests/index.spec.ts

1. Entry point를 class 형식으로 리펙토링 했습니다
- middleware 초기화
- controller 초기화
- DB 초기화
- Application 초기화
를 명시적으로 분리했습니다
2. Dependency Injection을 적용해 각 Domain(?)을 초기화 하도록 리펙토링 했습니다
- Domain이란 표현이 정확한지는 모르겠습니다 (하하;)
3. Spring처럼 Container가 따로 없으니까, 직접 초기화 메소드를 호출해야한다는 불편함이 있는것 같습니다
- 정확히 DI를 이해하고 사용한 건 아니여서, 올바르게 구현한 건지는 잘 모르겠습니다 하하하하
- Java의 interface를 지원하지 않으니까, 완벽한 SOLID는 어떻게 달성할 수 있을지 모르겠습니다 (공부 필요)

refactor#20 : Entry point (index.ts) 리펙토링 + Dependency Injection 적용

---

src/user/user.controller.ts
src/user/user.d.ts
src/user/user.repository.ts
src/user/user.service.ts

MySQL에 맞게, typeorm을 통해서 진짜 SQL 쿼리를 만들었다

refactor#27: 검색기능을 DB환경에 맞게 변경

---

src/entity/bookmark.entity.ts
src/entity/date.entity.ts
src/entity/recipeHasIngredient.entity.ts
src/entity/recipeHasTag.entity.ts
src/ingredient/ingredient.entity.ts
src/recipe/recipe.entity.ts
src/recipe/recipeDescription.entity.ts
src/tag/tag.entity.ts
src/user/subscribe.entity.ts
src/user/user.entity.ts

user
subscribe
recipe
bookmark
recipe description
tag
recipe has tag
ingredient
recipe has ingredient

feat#24 : TypeORM Entity 구성

---

src/index.ts
src/recipe/index.ts
src/recipe/recipe.controller.ts
src/recipe/recipe.d.ts
src/recipe/recipe.repository.ts
src/recipe/recipe.service.ts
src/tag/index.ts
src/tag/tag.controller.ts
src/tag/tag.d.ts
src/tag/tag.repository.ts
src/tag/tag.service.ts
src/user/user.repository.ts

Recipe, tag의 Controller, Service, Repository를 Class 형식으로 리펙토링
Depenedency Injection 사용

feat#32 : Recipe, tag Controller, Service, Repository 구성

---

src/helper/helper.ts
src/recipe/recipe.controller.ts
src/recipe/recipe.d.ts
src/recipe/recipe.repository.ts
src/recipe/recipe.service.ts
src/tag/tag.controller.ts
src/user/user.controller.ts

Feat#4 : '최근 날짜 정렬' 검색, '오늘 생성된 레시피 중, 좋아요 많은 순 정렬' 검색 구현 

---

src/entity/date.entity.ts
src/recipe/recipe.controller.ts
src/recipe/recipe.d.ts
src/recipe/recipe.entity.ts
src/recipe/recipe.repository.ts
src/recipe/recipe.service.ts
src/tag/tag.controller.ts
src/user/subscribe.entity.ts
src/user/user.controller.ts
src/user/user.entity.ts

1. 일단은 user_id = 3으로 하드코딩 했습니다 -> Authorization 기능이 구현되면 수정 예정

Feat#7 현재 접속한 유저가 구독한 쉐프들의 최신 레시피

---

src/index.ts
src/recipe/index.ts
src/recipe/recipe.d.ts
src/recipe/recipe.repository.ts
src/tag/index.ts
src/tag/tag.d.ts
src/tag/tag.repository.ts
src/user/index.ts
src/user/user.d.ts
src/user/user.repository.ts

기존에는 Entity까지 Repository에 주입했는데, Entity는 내부에서 직접 접근하도록 수정
기존에는 Connection 객체를 DI 했는데, 과도한 권한 부여라고 생각이 들어 Entity Manager만 주입

refactor#42 : Di 조정

---

src/index.ts
src/recipe-ingredient/recipe-ingredient.entity.ts
src/recipe/recipe.controller.ts
src/recipe/recipe.d.ts
src/recipe/recipe.repository.ts
src/recipe/recipe.service.ts

'재료로 레시피 검색' 기능 구현
- 리펙토링 필요
- request body에 어떤 형식으로 데이터 넘길지도 고민 필요

feat#39 : '재료로 레시피 검색' 기능 구현

---

src/recipe/recipe.controller.ts
src/recipe/recipe.d.ts
src/recipe/recipe.repository.ts
src/recipe/recipe.service.ts

feat#5 : PK로 recipe 찾기 구현

---

src/user/user.controller.ts
src/user/user.d.ts
src/user/user.entity.ts
src/user/user.repository.ts
src/user/user.service.ts

마이 페이지에서, '회원 정보 모달'을 통한 유저 정보 변경을 구현했습니다

feat#48 : 유저 정보 업데이트 구현

---

src/container.ts
src/entity/dateInfo.entity.ts
src/index.ts
src/recipe/recipe.entity.ts
src/user/user.entity.ts

embedded Entity 사용 방식이 잘못되어서, typeORM 권장 방식으로 수정했습니다

refactor : Date info Entity 리펙토링

---

src/container.ts
src/index.ts

App은 정상적으로 실행되는데, router가 등록 안 된 문제가 발생했다
1. index.ts에서 사용하는 app 객체를 container에 주입했더니 잘 됐다
원인은 잘 모르겠다 하하하;

Fix#59 router 등록

---

src/container.ts
src/subscribe/subscribe.controller.ts
src/subscribe/subscribe.repository.ts
src/subscribe/subscribe.service.ts
src/subscribe/type/subscribeController.d.ts
src/subscribe/type/subscribeRepository.d.ts
src/subscribe/type/subscribeService.d.ts
src/user/type/userRepository.d.ts
src/user/user.repository.ts

Feat#67 subscribe 구현

---

src/container.ts
src/ingredient/ingredient.entity.ts
src/recipe/recipe.entity.ts
src/recipe/recipe.repository.ts
src/recipe/recipe.service.ts
src/recipe/type/data.d.ts
src/recipe/type/recipeRepository.d.ts
src/recipe/type/recipeService.d.ts
src/recipeDescription/recipeDescription.entity.ts

refactor : 타입명 수정

---

src/bookmark/controller.ts
src/bookmark/service.ts
src/helper/helper.ts
src/recipe/controller.ts
src/recipe/service.ts
src/recipe/type/error.ts
src/recipe/type/service.d.ts
src/subscribe/controller.ts
src/subscribe/service.ts
src/subscribe/type/service.d.ts
src/tag/controller.ts
src/tag/repository.ts
src/tag/service.ts
src/tag/type/service.d.ts
src/user/controller.ts
src/user/service.ts
src/user/type/error.ts
src/user/type/service.d.ts

1. not found
2. not authorized
3. password not match
1. not found
1. server error

Refactor#86 exception

---

ormconfig.ts
package.json
src/container.ts
src/index.ts
yarn.lock

1. 기존에는 Test 환경만 존재함
2. AWS EC2에서 DB 서버를 구축함 -> Production용도로 사용
3. Test용도의 DB 서버는 Local에서 작동하도록 설정

config#90 실행환경 분리

---

src/user/controller.ts

제목: 회원가입  json syntax error 수정
내용: 회원가입 기능 부분에서 json body 에러가 나길래 중괄호만 없애서 올립니다!

refactor: 회원가입  json syntax error 수정

---

.gitignore
README.md
package.json
yarn.lock

develop branch가 업데이트 되어있길래 한 번 merge하고 진행하겠습니다!
추가로 README.md에는 기록할만한 것들을 적어봤습니다!
보고서에 어떻게 프로그램을 시작하는지도 설명하라고 해서 그것도 포맷되어서 다시 설치하는 김에 적어보았습니다...

Fix#94 bcrypt =>using updated develop branch

---

package.json
src/index.ts
src/user/controller.ts
src/user/entity.ts
src/user/service.ts
src/user/type/controller.d.ts
src/user/type/dto.ts
src/user/type/service.d.ts
yarn.lock

로그인, 인가, 로그아웃 구현 
- 기능 구현 
- 추후 리펙토링 필요
- api 이름 수정(기능이 많아지다보니 헷갈려서 이름을 붙였습니다!)

Feat#13 authorization middleware

---

src/container.ts
src/recipe/controller.ts
src/recipe/repository.ts
src/recipe/service.ts
src/recipe/type/controller.d.ts
src/recipe/type/repository.d.ts
src/recipe/type/service.d.ts
src/userIngredient/entity.ts
src/userIngredient/repository.ts
src/userIngredient/type/repository.d.ts

1. 사용자가 가장 많이 검색한 재료 키워드 6개를 찾음
2. 각 재료가 포함된 레시피를 찾음 (중복 제거)
3. 만약 재료가 6개 미만인 경우, 랜덤으로 레시피를 6개를 맞추도록 구현

Feat#100 user recommend recipe

---

src/user/controller.ts
src/user/service.ts
src/user/type/controller.d.ts
src/user/type/service.d.ts

제목: 로그인, 로그아웃 , 미들웨어 기능 추가 완료 
1. 구현기능 
- 로그인  
- 로그아웃
- 미들웨어
2. 미들웨어 기능 적용
- jwt userId 가져와서 회원정보 관련 삭제, 업데이트 수행
- 썸네일 업로드 / 썸네일 삭제 / 유저정보 업데이트 / 회원탈퇴 적용 및 확인 
3. 주의할 점 
- 추후 에러처리 좀 더 구체화 필요.

Refactor#106auth modify

---

src/container.ts
src/recipeTag/controller.ts
src/recipeTag/entity.ts
src/recipeTag/repository.ts
src/recipeTag/service.ts
src/recipeTag/type/controller.d.ts
src/recipeTag/type/repository.d.ts
src/recipeTag/type/service.d.ts

Feat#110 : 태그를 포함하는 레시피 찾기 API 구현
